# Generated by Django 5.2 on 2025-04-28 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BisSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bis_type",
                    models.CharField(
                        choices=[("출발", "출발 비스"), ("최종", "최종 비스")],
                        max_length=10,
                        verbose_name="비스 종류",
                    ),
                ),
            ],
            options={
                "verbose_name": "비스 세트",
                "verbose_name_plural": "비스 세트들",
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="아이템 이름")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("무기", "무기"),
                            ("모자", "모자"),
                            ("상의", "상의"),
                            ("장갑", "장갑"),
                            ("하의", "하의"),
                            ("신발", "신발"),
                            ("귀걸이", "귀걸이"),
                            ("목걸이", "목걸이"),
                            ("팔찌", "팔찌"),
                            ("반지1", "반지1"),
                            ("반지2", "반지2"),
                        ],
                        max_length=20,
                        verbose_name="아이템 종류",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("석판템", "석판템"),
                            ("보강석판템", "보강석판템"),
                            ("일반레이드템", "일반레이드템"),
                            ("영웅레이드템", "영웅레이드템"),
                            ("극만신템", "극만신템"),
                            ("제작템", "제작템"),
                        ],
                        max_length=20,
                        verbose_name="아이템 출처",
                    ),
                ),
                ("item_level", models.IntegerField(verbose_name="아이템 레벨")),
            ],
            options={
                "verbose_name": "아이템",
                "verbose_name_plural": "아이템들",
            },
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nickname",
                    models.CharField(max_length=50, unique=True, verbose_name="닉네임"),
                ),
                (
                    "job",
                    models.CharField(
                        choices=[
                            ("전사", "전사"),
                            ("나이트", "나이트"),
                            ("암흑기사", "암흑기사"),
                            ("건브레이커", "건브레이커"),
                            ("몽크", "몽크"),
                            ("용기사", "용기사"),
                            ("닌자", "닌자"),
                            ("사무라이", "사무라이"),
                            ("리퍼", "리퍼"),
                            ("바이퍼", "바이퍼"),
                            ("음유시인", "음유시인"),
                            ("기공사", "기공사"),
                            ("무도가", "무도가"),
                            ("흑마도사", "흑마도사"),
                            ("소환사", "소환사"),
                            ("적마도사", "적마도사"),
                            ("픽토맨서", "픽토맨서"),
                            ("백마도사", "백마도사"),
                            ("학자", "학자"),
                            ("점성술사", "점성술사"),
                            ("현자", "현자"),
                        ],
                        max_length=20,
                        verbose_name="직업",
                    ),
                ),
                (
                    "job_type",
                    models.CharField(
                        choices=[("탱커", "탱커"), ("딜러", "딜러"), ("힐러", "힐러")],
                        max_length=10,
                        verbose_name="직업 타입",
                    ),
                ),
            ],
            options={
                "verbose_name": "플레이어",
                "verbose_name_plural": "플레이어들",
            },
        ),
        migrations.CreateModel(
            name="RaidProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("raid_date", models.DateField(verbose_name="레이드 날짜")),
                (
                    "floor",
                    models.IntegerField(
                        choices=[(1, "1층"), (2, "2층"), (3, "3층"), (4, "4층")],
                        verbose_name="층수",
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True, verbose_name="메모")),
            ],
            options={
                "verbose_name": "레이드 진행",
                "verbose_name_plural": "레이드 진행들",
            },
        ),
        migrations.CreateModel(
            name="Season",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="시즌 이름")),
                ("start_date", models.DateField(verbose_name="시작 날짜")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="종료 날짜"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="활성화 여부"),
                ),
                (
                    "distribution_method",
                    models.CharField(
                        choices=[
                            ("먹고빠지기", "먹고빠지기"),
                            ("우선순위분배", "우선순위분배"),
                        ],
                        default="우선순위분배",
                        max_length=20,
                        verbose_name="분배 방식",
                    ),
                ),
            ],
            options={
                "verbose_name": "시즌",
                "verbose_name_plural": "시즌들",
            },
        ),
        migrations.CreateModel(
            name="BisItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slot",
                    models.CharField(
                        choices=[
                            ("무기", "무기"),
                            ("모자", "모자"),
                            ("상의", "상의"),
                            ("장갑", "장갑"),
                            ("하의", "하의"),
                            ("신발", "신발"),
                            ("귀걸이", "귀걸이"),
                            ("목걸이", "목걸이"),
                            ("팔찌", "팔찌"),
                            ("반지1", "반지1"),
                            ("반지2", "반지2"),
                        ],
                        max_length=20,
                        verbose_name="장착 슬롯",
                    ),
                ),
                (
                    "bis_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="bis_manager.bisset",
                        verbose_name="소속 비스 세트",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bis_items",
                        to="bis_manager.item",
                        verbose_name="아이템",
                    ),
                ),
            ],
            options={
                "verbose_name": "비스 아이템",
                "verbose_name_plural": "비스 아이템들",
                "unique_together": {("bis_set", "slot")},
            },
        ),
        migrations.AddField(
            model_name="bisset",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bis_sets",
                to="bis_manager.player",
                verbose_name="플레이어",
            ),
        ),
        migrations.CreateModel(
            name="ItemAcquisition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acquisitions",
                        to="bis_manager.item",
                        verbose_name="획득 아이템",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acquisitions",
                        to="bis_manager.player",
                        verbose_name="플레이어",
                    ),
                ),
                (
                    "raid_progress",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acquisitions",
                        to="bis_manager.raidprogress",
                        verbose_name="레이드 진행",
                    ),
                ),
            ],
            options={
                "verbose_name": "아이템 획득",
                "verbose_name_plural": "아이템 획득들",
            },
        ),
        migrations.AddField(
            model_name="raidprogress",
            name="season",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="raid_progresses",
                to="bis_manager.season",
                verbose_name="시즌",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="season",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="bis_manager.season",
                verbose_name="소속 시즌",
            ),
        ),
        migrations.AddField(
            model_name="bisset",
            name="season",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bis_sets",
                to="bis_manager.season",
                verbose_name="시즌",
            ),
        ),
        migrations.CreateModel(
            name="Materia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("무략", "무략"),
                            ("야망", "야망"),
                            ("심안", "심안"),
                            ("기술속도", "기술속도"),
                            ("시전속도", "시전속도"),
                            ("신앙", "신앙"),
                            ("강유", "강유"),
                        ],
                        max_length=20,
                        verbose_name="마테리쟈 종류",
                    ),
                ),
                ("slot_number", models.IntegerField(verbose_name="마테리쟈 슬롯 번호")),
                (
                    "bis_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materias",
                        to="bis_manager.bisitem",
                        verbose_name="소속 비스 아이템",
                    ),
                ),
            ],
            options={
                "verbose_name": "마테리쟈",
                "verbose_name_plural": "마테리쟈들",
                "unique_together": {("bis_item", "slot_number")},
            },
        ),
        migrations.CreateModel(
            name="ResourceTracking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("석판", "석판"),
                            ("낱장_1층", "1층 낱장"),
                            ("낱장_2층", "2층 낱장"),
                            ("낱장_3층", "3층 낱장"),
                            ("낱장_4층", "4층 낱장"),
                            ("경화약", "경화약"),
                            ("강화섬유", "강화섬유"),
                            ("무기석판", "무기석판"),
                        ],
                        max_length=20,
                        verbose_name="재화 종류",
                    ),
                ),
                (
                    "current_amount",
                    models.IntegerField(default=0, verbose_name="현재 보유량"),
                ),
                (
                    "total_needed",
                    models.IntegerField(default=0, verbose_name="총 필요량"),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="bis_manager.player",
                        verbose_name="플레이어",
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="bis_manager.season",
                        verbose_name="시즌",
                    ),
                ),
            ],
            options={
                "verbose_name": "재화 현황",
                "verbose_name_plural": "재화 현황들",
                "unique_together": {("player", "season", "resource_type")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="raidprogress",
            unique_together={("season", "raid_date", "floor")},
        ),
        migrations.CreateModel(
            name="DistributionPriority",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("무기", "무기"),
                            ("모자", "모자"),
                            ("상의", "상의"),
                            ("장갑", "장갑"),
                            ("하의", "하의"),
                            ("신발", "신발"),
                            ("귀걸이", "귀걸이"),
                            ("목걸이", "목걸이"),
                            ("팔찌", "팔찌"),
                            ("반지1", "반지1"),
                            ("반지2", "반지2"),
                        ],
                        max_length=20,
                        verbose_name="아이템 종류",
                    ),
                ),
                ("priority", models.IntegerField(verbose_name="우선순위")),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="distribution_priorities",
                        to="bis_manager.player",
                        verbose_name="플레이어",
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="distribution_priorities",
                        to="bis_manager.season",
                        verbose_name="시즌",
                    ),
                ),
            ],
            options={
                "verbose_name": "분배 우선순위",
                "verbose_name_plural": "분배 우선순위들",
                "unique_together": {("season", "player", "item_type")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="bisset",
            unique_together={("player", "season", "bis_type")},
        ),
    ]
