# Generated by Django 5.2 on 2025-05-07 08:22

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="BisSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bis_type",
                    models.CharField(
                        choices=[("출발", "출발 비스"), ("최종", "최종 비스")],
                        max_length=10,
                        verbose_name="비스 종류",
                    ),
                ),
            ],
            options={
                "verbose_name": "비스 세트",
                "verbose_name_plural": "비스 세트들",
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="아이템 이름")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("무기", "무기"),
                            ("모자", "모자"),
                            ("상의", "상의"),
                            ("장갑", "장갑"),
                            ("하의", "하의"),
                            ("신발", "신발"),
                            ("귀걸이", "귀걸이"),
                            ("목걸이", "목걸이"),
                            ("팔찌", "팔찌"),
                            ("반지1", "반지1"),
                            ("반지2", "반지2"),
                        ],
                        max_length=20,
                        verbose_name="아이템 종류",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("석판템", "석판템"),
                            ("보강석판템", "보강석판템"),
                            ("일반레이드템", "일반레이드템"),
                            ("영웅레이드템", "영웅레이드템"),
                            ("극만신템", "극만신템"),
                            ("제작템", "제작템"),
                        ],
                        max_length=20,
                        verbose_name="아이템 출처",
                    ),
                ),
                ("item_level", models.IntegerField(verbose_name="아이템 레벨")),
            ],
            options={
                "verbose_name": "아이템",
                "verbose_name_plural": "아이템들",
            },
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nickname",
                    models.CharField(max_length=50, unique=True, verbose_name="닉네임"),
                ),
                (
                    "job",
                    models.CharField(
                        choices=[
                            ("전사", "전사"),
                            ("나이트", "나이트"),
                            ("암흑기사", "암흑기사"),
                            ("건브레이커", "건브레이커"),
                            ("몽크", "몽크"),
                            ("용기사", "용기사"),
                            ("닌자", "닌자"),
                            ("사무라이", "사무라이"),
                            ("리퍼", "리퍼"),
                            ("바이퍼", "바이퍼"),
                            ("음유시인", "음유시인"),
                            ("기공사", "기공사"),
                            ("무도가", "무도가"),
                            ("흑마도사", "흑마도사"),
                            ("소환사", "소환사"),
                            ("적마도사", "적마도사"),
                            ("픽토맨서", "픽토맨서"),
                            ("백마도사", "백마도사"),
                            ("학자", "학자"),
                            ("점성술사", "점성술사"),
                            ("현자", "현자"),
                        ],
                        max_length=20,
                        verbose_name="직업",
                    ),
                ),
                (
                    "job_type",
                    models.CharField(
                        choices=[("탱커", "탱커"), ("딜러", "딜러"), ("힐러", "힐러")],
                        max_length=10,
                        verbose_name="직업 타입",
                    ),
                ),
            ],
            options={
                "verbose_name": "플레이어",
                "verbose_name_plural": "플레이어들",
            },
        ),
        migrations.CreateModel(
            name="RaidProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("raid_date", models.DateField(verbose_name="레이드 날짜")),
                (
                    "floor",
                    models.IntegerField(
                        choices=[(1, "1층"), (2, "2층"), (3, "3층"), (4, "4층")],
                        verbose_name="층수",
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True, verbose_name="메모")),
            ],
            options={
                "verbose_name": "레이드 진행",
                "verbose_name_plural": "레이드 진행들",
            },
        ),
        migrations.CreateModel(
            name="Season",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="시즌 이름")),
                ("start_date", models.DateField(verbose_name="시작 날짜")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="종료 날짜"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="활성화 여부"),
                ),
                (
                    "distribution_method",
                    models.CharField(
                        choices=[
                            ("먹고빠지기", "먹고빠지기"),
                            ("우선순위분배", "우선순위분배"),
                        ],
                        default="우선순위분배",
                        max_length=20,
                        verbose_name="분배 방식",
                    ),
                ),
            ],
            options={
                "verbose_name": "시즌",
                "verbose_name_plural": "시즌들",
            },
        ),
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "user_type",
                    models.CharField(
                        choices=[("regular", "공대원"), ("admin", "공대장")],
                        default="regular",
                        max_length=10,
                        verbose_name="회원 유형",
                    ),
                ),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="profile_images/",
                        verbose_name="프로필 이미지",
                    ),
                ),
                (
                    "profile_image_url",
                    models.URLField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="프로필 이미지 URL",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        related_name="custom_user_set",
                        related_query_name="custom_user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="custom_user_set",
                        related_query_name="custom_user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "사용자",
                "verbose_name_plural": "사용자들",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="BisItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slot",
                    models.CharField(
                        choices=[
                            ("무기", "무기"),
                            ("모자", "모자"),
                            ("상의", "상의"),
                            ("장갑", "장갑"),
                            ("하의", "하의"),
                            ("신발", "신발"),
                            ("귀걸이", "귀걸이"),
                            ("목걸이", "목걸이"),
                            ("팔찌", "팔찌"),
                            ("반지1", "반지1"),
                            ("반지2", "반지2"),
                        ],
                        max_length=20,
                        verbose_name="장착 슬롯",
                    ),
                ),
                (
                    "bis_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="bis_manager.bisset",
                        verbose_name="소속 비스 세트",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bis_items",
                        to="bis_manager.item",
                        verbose_name="아이템",
                    ),
                ),
            ],
            options={
                "verbose_name": "비스 아이템",
                "verbose_name_plural": "비스 아이템들",
                "unique_together": {("bis_set", "slot")},
            },
        ),
        migrations.AddField(
            model_name="bisset",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bis_sets",
                to="bis_manager.player",
                verbose_name="플레이어",
            ),
        ),
        migrations.CreateModel(
            name="ItemAcquisition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acquisitions",
                        to="bis_manager.item",
                        verbose_name="획득 아이템",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acquisitions",
                        to="bis_manager.player",
                        verbose_name="플레이어",
                    ),
                ),
                (
                    "raid_progress",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acquisitions",
                        to="bis_manager.raidprogress",
                        verbose_name="레이드 진행",
                    ),
                ),
            ],
            options={
                "verbose_name": "아이템 획득",
                "verbose_name_plural": "아이템 획득들",
            },
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="일정 제목")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="일정 설명"),
                ),
                ("start_time", models.DateTimeField(verbose_name="시작 시간")),
                ("end_time", models.DateTimeField(verbose_name="종료 시간")),
                (
                    "is_admin_schedule",
                    models.BooleanField(default=False, verbose_name="관리자 일정 여부"),
                ),
                (
                    "repeat_type",
                    models.CharField(
                        choices=[
                            ("none", "반복 없음"),
                            ("daily", "매일"),
                            ("weekly", "매주"),
                            ("monthly", "매월"),
                        ],
                        default="none",
                        max_length=10,
                        verbose_name="반복 유형",
                    ),
                ),
                (
                    "repeat_days",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="반복 요일 (쉼표로 구분 1-7, 1:월요일)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 시간"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정 시간"),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_schedules",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="작성자",
                    ),
                ),
            ],
            options={
                "verbose_name": "일정",
                "verbose_name_plural": "일정들",
            },
        ),
        migrations.AddField(
            model_name="raidprogress",
            name="season",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="raid_progresses",
                to="bis_manager.season",
                verbose_name="시즌",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="season",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="bis_manager.season",
                verbose_name="소속 시즌",
            ),
        ),
        migrations.AddField(
            model_name="bisset",
            name="season",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bis_sets",
                to="bis_manager.season",
                verbose_name="시즌",
            ),
        ),
        migrations.CreateModel(
            name="Materia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("무략", "무략"),
                            ("야망", "야망"),
                            ("심안", "심안"),
                            ("기술속도", "기술속도"),
                            ("시전속도", "시전속도"),
                            ("신앙", "신앙"),
                            ("강유", "강유"),
                        ],
                        max_length=20,
                        verbose_name="마테리쟈 종류",
                    ),
                ),
                ("slot_number", models.IntegerField(verbose_name="마테리쟈 슬롯 번호")),
                (
                    "bis_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materias",
                        to="bis_manager.bisitem",
                        verbose_name="소속 비스 아이템",
                    ),
                ),
            ],
            options={
                "verbose_name": "마테리쟈",
                "verbose_name_plural": "마테리쟈들",
                "unique_together": {("bis_item", "slot_number")},
            },
        ),
        migrations.CreateModel(
            name="ResourceTracking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("석판", "석판"),
                            ("낱장_1층", "1층 낱장"),
                            ("낱장_2층", "2층 낱장"),
                            ("낱장_3층", "3층 낱장"),
                            ("낱장_4층", "4층 낱장"),
                            ("경화약", "경화약"),
                            ("강화섬유", "강화섬유"),
                            ("무기석판", "무기석판"),
                        ],
                        max_length=20,
                        verbose_name="재화 종류",
                    ),
                ),
                (
                    "current_amount",
                    models.IntegerField(default=0, verbose_name="현재 보유량"),
                ),
                (
                    "total_needed",
                    models.IntegerField(default=0, verbose_name="총 필요량"),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="bis_manager.player",
                        verbose_name="플레이어",
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="bis_manager.season",
                        verbose_name="시즌",
                    ),
                ),
            ],
            options={
                "verbose_name": "재화 현황",
                "verbose_name_plural": "재화 현황들",
                "unique_together": {("player", "season", "resource_type")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="raidprogress",
            unique_together={("season", "raid_date", "floor")},
        ),
        migrations.CreateModel(
            name="DistributionPriority",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("무기", "무기"),
                            ("모자", "모자"),
                            ("상의", "상의"),
                            ("장갑", "장갑"),
                            ("하의", "하의"),
                            ("신발", "신발"),
                            ("귀걸이", "귀걸이"),
                            ("목걸이", "목걸이"),
                            ("팔찌", "팔찌"),
                            ("반지1", "반지1"),
                            ("반지2", "반지2"),
                        ],
                        max_length=20,
                        verbose_name="아이템 종류",
                    ),
                ),
                ("priority", models.IntegerField(verbose_name="우선순위")),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="distribution_priorities",
                        to="bis_manager.player",
                        verbose_name="플레이어",
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="distribution_priorities",
                        to="bis_manager.season",
                        verbose_name="시즌",
                    ),
                ),
            ],
            options={
                "verbose_name": "분배 우선순위",
                "verbose_name_plural": "분배 우선순위들",
                "unique_together": {("season", "player", "item_type")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="bisset",
            unique_together={("player", "season", "bis_type")},
        ),
    ]
