# Generated by Django 5.2 on 2025-05-13 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bis_manager", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="nickname",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="인게임 캐릭터 이름"
            ),
        ),
    ]
