# Generated by Django 5.2 on 2025-05-13 05:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bis_manager", "0002_customuser_nickname"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="players",
                to=settings.AUTH_USER_MODEL,
                verbose_name="연결된 사용자",
            ),
        ),
    ]
