# Generated by Django 5.2 on 2025-05-13 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bis_manager", "0003_player_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="profile_image_url",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="프로필 이미지 URL"
            ),
        ),
    ]
